"""Word-level AIGT/HWT boundary detector.

This module provides :class:`WordLevelDetector`, which performs token-level
classification to determine whether each word in a given text was written by
a human (HWT) or generated by AI (AIGT). It supports:

* **Model-based inference** using a fine-tuned DeBERTa + CRF architecture
  with sliding-window processing.
* **Heuristic fallback** when the model or its dependencies are unavailable.
* **Sentence-aware refinement** that leverages sentence-level predictions
  to locate word-level switch boundaries more precisely.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
import time
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Any

import numpy as np

from ..config import WORD_BOUNDARY_BACKEND_SCRIPT, WORD_MODEL_NAME, WORD_MODEL_PATH
from .utils import split_sentences, tokenize_with_spans

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# 常量与枚举
# ---------------------------------------------------------------------------

class LabelID(IntEnum):
    """Token-level label enumeration.

    Attributes:
        HWT: Human-Written Text (label id = 0).
        AIGT: AI-Generated Text (label id = 1).
    """

    HWT = 0
    AIGT = 1

    @property
    def display_name(self) -> str:
        """Return the human-readable label string."""
        return "AIGT" if self == LabelID.AIGT else "HWT"

    @classmethod
    def from_string(cls, label: str) -> "LabelID":
        """Parse a label string (case-insensitive) into a LabelID.

        Args:
            label: A string such as ``"AIGT"`` or ``"HWT"``.

        Returns:
            The corresponding :class:`LabelID` member.
        """
        return cls.AIGT if label.strip().upper() == "AIGT" else cls.HWT


# ---------------------------------------------------------------------------
# 数据结构
# ---------------------------------------------------------------------------

@dataclass
class WordPredictResult:
    """Container for word-level prediction results.

    Attributes:
        words: A list of per-token dictionaries, each containing at least
            ``token``, ``start``, ``end``, ``label``, ``label_id``, and
            ``confidence`` keys.
        switch_word_index: The index of the first token where the predicted
            label changes, or ``0`` if no switch is detected.
        model_used: A short identifier describing which model or heuristic
            produced this result.
    """

    words: list[dict[str, Any]]
    switch_word_index: int
    model_used: str

    @property
    def ai_ratio(self) -> float:
        """Return the fraction of tokens classified as AIGT.

        Returns:
            A float in ``[0.0, 1.0]``, or ``0.0`` when there are no tokens.
        """
        if not self.words:
            return 0.0
        ai_count = sum(1 for w in self.words if w.get("label_id") == LabelID.AIGT)
        return ai_count / len(self.words)

    def to_dict(self) -> dict[str, Any]:
        """Serialize this result to a plain dictionary.

        Returns:
            A dictionary suitable for JSON serialization.
        """
        return {
            "words": self.words,
            "switch_word_index": self.switch_word_index,
            "model_used": self.model_used,
            "ai_ratio": round(self.ai_ratio, 4),
        }


# ---------------------------------------------------------------------------
# 检测器
# ---------------------------------------------------------------------------

class WordLevelDetector:
    """Word-level detector that classifies each token as HWT or AIGT.

    The detector first attempts to load a DeBERTa-CRF model from the paths
    specified in the application configuration.  If loading fails (missing
    dependencies, corrupt checkpoint, etc.), it transparently falls back to
    a lightweight heuristic based on token-length gradients.

    The class supports the context-manager protocol for automatic resource
    cleanup::

        with WordLevelDetector() as detector:
            result = detector.predict("Some text to analyse.")

    Class Attributes:
        BASE_WINDOW: Sliding-window size (in tokens) for model inference.
        BASE_STRIDE: Stride between consecutive windows.
        SHORT_WINDOW_CAP: Maximum window size for short-text optimisation.
        NUM_LABELS: Number of output label classes (HWT + AIGT).
        FALLBACK_BASE_CONFIDENCE: Base confidence score in fallback mode.
        FALLBACK_MAX_CONFIDENCE_BOOST: Maximum additive confidence boost.
        FALLBACK_CONFIDENCE_STEP: Per-token confidence increment.
        DEFAULT_TOKEN_CONFIDENCE: Initial confidence for unlabelled tokens.
        SENTENCE_TOKEN_CONFIDENCE: Confidence after sentence-level assignment.
        SWITCH_REFINED_CONFIDENCE: Confidence after boundary refinement.
        BACKEND_TIMEOUT_SECONDS: Timeout for the external boundary subprocess.
        HEURISTIC_MIN_TOKENS_FOR_CONV: Minimum token count to use convolution.
        MAX_LOAD_RETRIES: Number of retry attempts for model loading.
        LOAD_RETRY_DELAY_SECONDS: Delay between retry attempts.
    """

    # -- 模型推理参数 --
    BASE_WINDOW: int = 512
    BASE_STRIDE: int = 384
    SHORT_WINDOW_CAP: int = 256
    NUM_LABELS: int = 2

    # -- 置信度参数 --
    FALLBACK_BASE_CONFIDENCE: float = 0.55
    FALLBACK_MAX_CONFIDENCE_BOOST: float = 0.4
    FALLBACK_CONFIDENCE_STEP: float = 0.03
    DEFAULT_TOKEN_CONFIDENCE: float = 0.65
    SENTENCE_TOKEN_CONFIDENCE: float = 0.70
    SWITCH_REFINED_CONFIDENCE: float = 0.88

    # -- 运行时参数 --
    BACKEND_TIMEOUT_SECONDS: int = 45
    HEURISTIC_MIN_TOKENS_FOR_CONV: int = 4
    MAX_LOAD_RETRIES: int = 2
    LOAD_RETRY_DELAY_SECONDS: float = 1.0

    # ------------------------------------------------------------------
    # 初始化与资源管理
    # ------------------------------------------------------------------

    def __init__(self) -> None:
        """Initialise the detector and attempt to load the model.

        If the model file does not exist or loading fails after all retries,
        the detector enters *fallback mode* (``self.ready == False``).
        """
        self.model: Any = None
        self.tokenizer: Any = None
        self.device: Any = None
        self.ready: bool = False
        self.max_len: int = self.BASE_WINDOW
        self._torch: Any = None
        self._infer_fn: Any = None

        self._load_model_with_retry()

    def _load_model_with_retry(self) -> None:
        """Attempt to load the model, retrying on failure.

        Makes at most ``MAX_LOAD_RETRIES + 1`` attempts.  If all attempts
        fail the detector remains in fallback mode.
        """
        model_path = str(WORD_MODEL_PATH)
        if not os.path.isfile(model_path):
            logger.warning(
                "Model file does not exist: %s. Entering fallback mode directly.",
                model_path,
            )
            return

        total_attempts = self.MAX_LOAD_RETRIES + 1
        last_exc: Exception | None = None

        for attempt in range(1, total_attempts + 1):
            try:
                self._do_load_model()
                return
            except Exception as exc:
                last_exc = exc
                logger.warning(
                    "Model load attempt %d/%d failed: %s",
                    attempt, total_attempts, exc,
                )
                if attempt < total_attempts:
                    time.sleep(self.LOAD_RETRY_DELAY_SECONDS)

        logger.warning(
            "All %d model load attempts exhausted. Fallback mode enabled. Last error: %s",
            total_attempts, last_exc,
            exc_info=True,
        )

    def _do_load_model(self) -> None:
        """Perform a single model-loading attempt.

        Raises:
            Exception: Any exception raised by ``torch``, ``transformers``,
                or the custom model runtime is propagated to the caller.
        """
        import torch
        from transformers import AutoTokenizer

        from .word_model_runtime import (
            DeBERTaCRFTagger,
            infer_document_with_sliding_windows,
        )

        self._torch = torch
        self._infer_fn = infer_document_with_sliding_windows
        self.tokenizer = AutoTokenizer.from_pretrained(WORD_MODEL_NAME)
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = DeBERTaCRFTagger(WORD_MODEL_NAME, self.NUM_LABELS).to(self.device)

        ckpt = torch.load(WORD_MODEL_PATH, map_location=self.device, weights_only=False)
        state = ckpt.get("model_state_dict", ckpt)
        self.model.load_state_dict(state)
        self.model.eval()

        self.ready = True
        logger.info(
            "Word model loaded successfully from %s on %s",
            WORD_MODEL_PATH, self.device,
        )

    def close(self) -> None:
        """Release model resources and clear GPU cache (if applicable)."""
        if self.model is not None:
            del self.model
            self.model = None
        if self.tokenizer is not None:
            del self.tokenizer
            self.tokenizer = None
        self.ready = False
        try:
            import torch
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        except ImportError:
            pass
        logger.info("WordLevelDetector resources released.")

    def __enter__(self) -> "WordLevelDetector":
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        self.close()

    # ------------------------------------------------------------------
    # 内部辅助方法
    # ------------------------------------------------------------------

    @staticmethod
    def _build_word_row(
        token_item: dict[str, Any],
        label_id: int | LabelID,
        confidence: float,
    ) -> dict[str, Any]:
        """Construct a single word-result dictionary.

        Args:
            token_item: The raw token dict from ``tokenize_with_spans``.
            label_id: Integer or :class:`LabelID` indicating the predicted class.
            confidence: Confidence score in ``[0, 1]``.

        Returns:
            A merged dictionary containing the original token fields plus
            ``label``, ``label_id``, and ``confidence``.
        """
        lid = LabelID(int(label_id))
        return {
            **token_item,
            "label": lid.display_name,
            "label_id": int(lid),
            "confidence": round(float(confidence), 4),
        }

    def _heuristic_split_index(self, tokens: list[dict[str, Any]]) -> int:
        """Compute a heuristic switch-point index based on token-length gradient.

        For very short token sequences (fewer than
        ``HEURISTIC_MIN_TOKENS_FOR_CONV`` tokens), a simple midpoint is
        returned instead.

        Args:
            tokens: List of token dictionaries produced by
                ``tokenize_with_spans``.

        Returns:
            The estimated index where the label switches.
        """
        n = len(tokens)
        if n <= 1:
            return 0
        if n < self.HEURISTIC_MIN_TOKENS_FOR_CONV:
            return n // 2

        lengths = np.array([len(t["token"]) for t in tokens], dtype=np.float32)
        smooth = np.convolve(lengths, np.ones(3) / 3.0, mode="same")
        grad = np.abs(np.diff(smooth, prepend=smooth[0]))
        return int(np.argmax(grad))

    def _compute_fallback_confidence(self, token_index: int, split_index: int) -> float:
        """Compute the confidence score for a token in fallback mode.

        The confidence grows linearly with the distance from the estimated
        split point, capped at ``FALLBACK_BASE_CONFIDENCE +
        FALLBACK_MAX_CONFIDENCE_BOOST``.

        Args:
            token_index: Position of the token in the sequence.
            split_index: Position of the estimated switch point.

        Returns:
            A confidence value in ``[0, 1]``.
        """
        return self.FALLBACK_BASE_CONFIDENCE + min(
            self.FALLBACK_MAX_CONFIDENCE_BOOST,
            abs(token_index - split_index) * self.FALLBACK_CONFIDENCE_STEP,
        )

    @staticmethod
    def _compute_first_switch_word_index(labels: list[int]) -> int:
        """Find the index just before the first label change.

        Args:
            labels: A list of integer label IDs (one per token).

        Returns:
            The index *before* the first position where the label differs
            from its predecessor, or ``0`` if all labels are identical.
        """
        for idx in range(1, len(labels)):
            if labels[idx] != labels[idx - 1]:
                return idx - 1
        return 0

    # ------------------------------------------------------------------
    # 核心推理方法
    # ------------------------------------------------------------------

    def _fallback_predict(self, text: str) -> WordPredictResult:
        """Run heuristic-based prediction when the model is unavailable.

        Args:
            text: The input text to analyse.

        Returns:
            A :class:`WordPredictResult` with ``model_used="fallback-heuristic"``.

        Raises:
            TypeError: If *text* is not a string.
        """
        if not isinstance(text, str):
            raise TypeError(f"Expected str, got {type(text).__name__}")
        text = text.strip()

        tokens = tokenize_with_spans(text)
        if not tokens:
            return WordPredictResult(words=[], switch_word_index=0, model_used="fallback-heuristic")

        split_idx = self._heuristic_split_index(tokens)

        words: list[dict[str, Any]] = []
        for i, item in enumerate(tokens):
            label_id = LabelID.AIGT if i > split_idx else LabelID.HWT
            confidence = self._compute_fallback_confidence(i, split_idx)
            words.append(self._build_word_row(item, label_id, confidence))

        return WordPredictResult(
            words=words,
            switch_word_index=split_idx,
            model_used="fallback-heuristic",
        )

    def predict(self, text: str) -> WordPredictResult:
        """Run word-level prediction on the given text.

        If the model is loaded, DeBERTa-CRF sliding-window inference is used.
        Otherwise, the heuristic fallback is invoked.

        Args:
            text: The input text to analyse.  Leading/trailing whitespace
                is stripped before processing.

        Returns:
            A :class:`WordPredictResult` containing per-token predictions.

        Raises:
            TypeError: If *text* is not a string.
        """
        if not isinstance(text, str):
            raise TypeError(f"Expected str, got {type(text).__name__}")
        text = text.strip()

        if not self.ready:
            return self._fallback_predict(text)

        tokens = tokenize_with_spans(text)
        words = [t["token"] for t in tokens]
        if not words:
            return WordPredictResult(words=[], switch_word_index=0, model_used="deberta-crf")

        t0 = time.monotonic()
        pred_labels, boundary, vote_counts = self._infer_fn(
            self.model,
            words,
            self.tokenizer,
            self.max_len,
            self.device,
            base_window=self.BASE_WINDOW,
            base_stride=self.BASE_STRIDE,
            short_window_cap=self.SHORT_WINDOW_CAP,
        )
        elapsed = time.monotonic() - t0
        logger.debug("predict() inference completed in %.3fs for %d tokens", elapsed, len(tokens))

        rows: list[dict[str, Any]] = []
        for i, token_item in enumerate(tokens):
            vote0 = int(vote_counts[i, 0]) if i < vote_counts.shape[0] else 0
            vote1 = int(vote_counts[i, 1]) if i < vote_counts.shape[0] else 0
            total = max(1, vote0 + vote1)
            conf = max(vote0, vote1) / total
            label_id = int(pred_labels[i]) if i < len(pred_labels) else LabelID.HWT
            rows.append(self._build_word_row(token_item, label_id, conf))

        return WordPredictResult(
            words=rows,
            switch_word_index=int(boundary),
            model_used="deberta-crf",
        )

    # ------------------------------------------------------------------
    # 句子感知推理
    # ------------------------------------------------------------------

    def _sentence_spans(
        self,
        text: str,
        sentence_rows: list[dict[str, Any]],
    ) -> list[tuple[int, int, str]]:
        """Map sentence rows to ``(start, end, label)`` spans within *text*.

        Uses sequential ``str.find`` to locate each sentence in the original
        text, advancing a cursor to preserve ordering.

        Args:
            text: The full document text.
            sentence_rows: A list of dicts with ``"text"`` and ``"label"`` keys.

        Returns:
            A list of ``(start_char, end_char, label_str)`` tuples.
        """
        spans: list[tuple[int, int, str]] = []
        cursor = 0
        for row in sentence_rows:
            sent = str(row.get("text", "")).strip()
            if not sent:
                continue

            start = text.find(sent, cursor)
            if start < 0:
                # Fallback: search from the beginning
                start = text.find(sent)
            if start < 0:
                start = cursor
            if start < cursor:
                start = cursor

            end = start + len(sent)
            cursor = end

            label = LabelID.from_string(str(row.get("label", ""))).display_name
            spans.append((start, end, label))
        return spans

    def _init_token_labels_from_sentences(
        self,
        tokens: list[dict[str, Any]],
        spans: list[tuple[int, int, str]],
    ) -> tuple[list[int], list[float], list[list[int]]]:
        """Initialise token labels and confidences from sentence-level spans.

        Args:
            tokens: Token list from ``tokenize_with_spans``.
            spans: Sentence spans from :meth:`_sentence_spans`.

        Returns:
            A tuple of ``(token_labels, token_conf, sentence_token_indices)``.
        """
        token_labels: list[int] = [int(LabelID.HWT)] * len(tokens)
        token_conf: list[float] = [self.DEFAULT_TOKEN_CONFIDENCE] * len(tokens)
        sentence_token_indices: list[list[int]] = []

        for start, end, sent_label in spans:
            idxs = [
                i for i, tok in enumerate(tokens)
                if tok["start"] >= start and tok["end"] <= end
            ]
            sentence_token_indices.append(idxs)
            label_id = int(LabelID.from_string(sent_label))
            for i in idxs:
                token_labels[i] = label_id
                token_conf[i] = self.SENTENCE_TOKEN_CONFIDENCE

        return token_labels, token_conf, sentence_token_indices

    def _resolve_local_boundary(
        self,
        local_text: str,
        combined_idxs: list[int],
    ) -> int:
        """Determine the word-level boundary within a local two-sentence window.

        First tries the external backend script; falls back to this
        detector's own :meth:`predict` if the external call returns ``None``.

        Args:
            local_text: Concatenated text of two adjacent sentences.
            combined_idxs: Token indices covering both sentences.

        Returns:
            A boundary index clamped to ``[0, len(combined_idxs) - 1]``.
        """
        local_boundary = self._call_external_boundary_backend(local_text)
        if local_boundary is None:
            local_res = self.predict(local_text)
            local_boundary = int(local_res.switch_word_index)
        return max(0, min(local_boundary, len(combined_idxs) - 1))

    def _refine_boundaries_at_switches(
        self,
        text: str,
        spans: list[tuple[int, int, str]],
        sentence_token_indices: list[list[int]],
        token_labels: list[int],
        token_conf: list[float],
    ) -> None:
        """Refine token labels at sentence-level switch points.

        For each pair of adjacent sentences with different labels, the
        method extracts the local text, determines a fine-grained boundary,
        and re-assigns token labels accordingly.

        This method modifies *token_labels* and *token_conf* **in place**.

        Args:
            text: The full document text.
            spans: Sentence spans.
            sentence_token_indices: Per-sentence token index lists.
            token_labels: Mutable list of token label IDs.
            token_conf: Mutable list of token confidence values.
        """
        for i in range(len(spans) - 1):
            left_label = spans[i][2]
            right_label = spans[i + 1][2]
            if left_label == right_label:
                continue

            left_idxs = sentence_token_indices[i]
            right_idxs = sentence_token_indices[i + 1]
            combined_idxs = left_idxs + right_idxs
            if not combined_idxs:
                continue

            left_text = text[spans[i][0]:spans[i][1]].strip()
            right_text = text[spans[i + 1][0]:spans[i + 1][1]].strip()
            local_text = f"{left_text} {right_text}".strip()
            if not local_text:
                continue

            local_boundary = self._resolve_local_boundary(local_text, combined_idxs)
            boundary_global = combined_idxs[local_boundary]

            left_id = int(LabelID.from_string(left_label))
            right_id = int(LabelID.from_string(right_label))

            for gi in combined_idxs:
                token_labels[gi] = left_id if gi <= boundary_global else right_id
                token_conf[gi] = self.SWITCH_REFINED_CONFIDENCE

    def _call_external_boundary_backend(self, text: str) -> int | None:
        """Invoke an external Python script to detect the word-level boundary.

        The script is expected to print a JSON object with a
        ``boundary_idx`` field to stdout.

        Args:
            text: The local text snippet to analyse.

        Returns:
            The boundary index reported by the backend, or ``None`` if the
            backend is unavailable or fails.
        """
        script_path = str(WORD_BOUNDARY_BACKEND_SCRIPT or "").strip()
        if not script_path:
            return None

        cmd: list[str] = [
            sys.executable,
            script_path,
            "--single_text", text,
            "--output_json",
            "--model_name", WORD_MODEL_NAME,
            "--best_model_path", WORD_MODEL_PATH,
            "--max_len", str(self.max_len),
        ]

        try:
            completed = subprocess.run(
                cmd,
                check=True,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="ignore",
                timeout=self.BACKEND_TIMEOUT_SECONDS,
            )
            payload = json.loads(completed.stdout.strip())
            boundary_idx = int(payload.get("boundary_idx", 0))
            logger.debug("External backend returned boundary_idx=%d", boundary_idx)
            return boundary_idx

        except subprocess.TimeoutExpired:
            logger.warning(
                "External boundary backend timed out after %ds",
                self.BACKEND_TIMEOUT_SECONDS,
            )
            return None
        except subprocess.CalledProcessError as exc:
            stderr_snippet = (exc.stderr or "")[:200]
            logger.warning(
                "External boundary backend failed (exit=%s): %s",
                exc.returncode, stderr_snippet,
            )
            return None
        except (json.JSONDecodeError, ValueError, KeyError) as exc:
            logger.warning("Failed to parse external backend output: %s", exc)
            return None
        except Exception as exc:
            logger.warning("Unexpected error calling external backend: %s", exc)
            return None

    def predict_with_sentence_switches(
        self,
        text: str,
        sentence_rows: list[dict[str, Any]],
    ) -> WordPredictResult:
        """Run prediction that is aware of sentence-level label switches.

        This method first assigns token labels based on sentence-level
        predictions, then refines boundaries at switch points using the
        word-level model (or heuristic fallback).

        Args:
            text: The full document text.
            sentence_rows: A list of sentence-level prediction dicts, each
                containing ``"text"`` and ``"label"`` keys.

        Returns:
            A :class:`WordPredictResult` with
            ``model_used="switch-aware-deberta-crf"`` (or fallback variant).

        Raises:
            TypeError: If *text* is not a string or *sentence_rows* is not a list.
        """
        if not isinstance(text, str):
            raise TypeError(f"Expected str, got {type(text).__name__}")
        if not isinstance(sentence_rows, list):
            raise TypeError(
                f"Expected list for sentence_rows, got {type(sentence_rows).__name__}"
            )

        text = text.strip()
        tokens = tokenize_with_spans(text)
        if not tokens:
            return WordPredictResult(
                words=[], switch_word_index=0, model_used="switch-aware-empty"
            )

        if not sentence_rows:
            return self.predict(text)

        spans = self._sentence_spans(text, sentence_rows)
        if not spans:
            return self.predict(text)

        # Step 1: Initialise token labels from sentence-level predictions.
        token_labels, token_conf, sentence_token_indices = (
            self._init_token_labels_from_sentences(tokens, spans)
        )

        # Step 2: Refine boundaries at sentence switch points.
        self._refine_boundaries_at_switches(
            text, spans, sentence_token_indices, token_labels, token_conf,
        )

        # Step 3: Assemble final result.
        rows: list[dict[str, Any]] = [
            self._build_word_row(tok, token_labels[i], token_conf[i])
            for i, tok in enumerate(tokens)
        ]

        switch_idx = self._compute_first_switch_word_index(token_labels)
        return WordPredictResult(
            words=rows,
            switch_word_index=switch_idx,
            model_used="switch-aware-deberta-crf",
        )